### ISSUE TITLE
Changes are not applied in the Calculated values and options tab

### ISSUE THREAD

**Issue by zhenyazb** [Haulmont/jmix-dynattr#32]
1. Create dynamic attribute with String value type.
2. Check **Lookup field**.
3. Go to the **Calculated values and options** tab.
4. Select **Options type** - Groovy.
5. Enter scripts in the **Options loader scripts** and **Recalculation value script** fields.
6. Click **OK**.
7. Click **OK**.
8. Click **Apply changes**.
9. Edit created attribute, change **Options type** to SQL, make changes in scripts.
10. Apply changes.
11.  Open attribute for editing.

Actual result: changes are not applied.
Expected result: changes are applied.

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-dynattr#57
