### ISSUE TITLE
Constraint Wizard is not available

### ISSUE THREAD

**Issue by zhenyazb** [Haulmont/jmix-dynattr#33]
1. Create a new dynamic attribute with Entity type.
2. Select Entity class.
3. Check **Lookup field**.
4. Go to the **Calculated values and options** tab.
5. Select **Options type** - JPQL.
6. Click **Constraint Wizard**.

Actual result: nothing happens.
Expected result: Constraint Wizard window is opened.

**Comment by knstvk** [comment]
Let's remove this button.
