### ISSUE TITLE
Predefined roles

### ISSUE THREAD

**Issue by alexbudarov** [Haulmont/jmix-dynattr#38]
CUBA had design-time roles for dynamic attributes:
![image](https://user-images.githubusercontent.com/6158807/108735856-7374db80-754a-11eb-9bf8-eab5eddc5734.png)

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2838-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

for admin role:
no validation script
![image](https://user-images.githubusercontent.com/66992566/117132660-3338a180-adb4-11eb-9f5e-782b908d4a45.png)
no groovy scripts
![image](https://user-images.githubusercontent.com/66992566/117132706-43508100-adb4-11eb-81a7-272486bf2c77.png)
impossible to add target screen
![image](https://user-images.githubusercontent.com/66992566/117132738-4ea3ac80-adb4-11eb-8ab9-3dab1334e21a.png)


for read-only role:
vied dynamic attr category>view attribute>Cancel
![image](https://user-images.githubusercontent.com/66992566/117132989-b6f28e00-adb4-11eb-81d0-37b38a3aaad3.png)

AR: You have unsaved changes
Click Save
AR: Access denied
![image](https://user-images.githubusercontent.com/66992566/117133053-c96cc780-adb4-11eb-892a-a76c321dff52.png)

**Comment by maistrenkoIulia** [comment]
user with dynattr admin role:
![image](https://user-images.githubusercontent.com/66992566/120440176-5dba5200-c394-11eb-838f-a6c0a8051927.png)
![image](https://user-images.githubusercontent.com/66992566/120440291-7165b880-c394-11eb-8eda-76faf91ccaec.png)

impossible to input value in localization tab 
![image](https://user-images.githubusercontent.com/66992566/120441773-fa312400-c395-11eb-9b92-9dc8ef82a61d.png)


read-only user:
dynamic attributes>view category>attributes location> make some changes in attributes configuration>cancel
in appeared dialog 'you have unsaved changes' click Save
AR: access denied
![image](https://user-images.githubusercontent.com/66992566/120447132-534f8680-c39b-11eb-9b81-20c113bf23eb.png)

dynamic attributes>categories>select category
ER: Apply changes button shouldn't be enabled
AR: Apply changes button is enabled

**Comment by bulgakovea** [comment]
Issue with unsaved changes should be fixed in Haulmont/jmix-dynattr#75

**Comment by maistrenkoIulia** [comment]
1. unnecessary inlinу editor for read-only role in localisation tabs
![image.png](https://images.zenhubusercontent.com/5f0d7237622df466164dea0a/e8e9ddb6-e495-43b6-b306-16c7f5e9f676)

2. dynamic attributes>categories>select category
ER: Apply changes button shouldn't be enabled
AR: Apply changes button is enabled 
![image.png](https://images.zenhubusercontent.com/5f0d7237622df466164dea0a/cd9cba49-cc33-47a1-864e-da13e132f123)

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT3070-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

impossiblу to set values in localiz screen by user with admin-role
![image](https://user-images.githubusercontent.com/66992566/122224047-c80ae080-cec4-11eb-8dff-f165d4cb4c3c.png)


for read-only user View button should be available
![image](https://user-images.githubusercontent.com/66992566/122224442-2afc7780-cec5-11eb-8dc4-51396000f28b.png)

**Comment by maistrenkoIulia** [comment]
1.0.0 - ok
1.1.0 - ok

localisation problem extracted to issue https://github.com/Haulmont/jmix-dynattr/issues/83
