### ISSUE TITLE
No options in dropdown list for Add Target screen

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#42]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: 
run app>dynamic attr>create category>select entity type = peson
create attribute (any type) >Visibility tab>Add Targer Screen
ER:person editor/person browser screen should be in dropdown list
AR: empty list

![image](https://user-images.githubusercontent.com/66992566/109971568-d49d6b80-7d0f-11eb-8e07-ec36f23d09b0.png)

**Comment by andreysubbotin** [comment]
Add `dynamicAttributes` facet into a screen
