### ISSUE TITLE
Change type of 'default date is current' for date without time attr to boolean

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#46]
Change type of 'default date is current' for date without time attr to boolean
TC: create dynamic attr with type = date without time / date
ER: 'default date is current' should be boolean (like it was in cuba)
AR:
![image](https://user-images.githubusercontent.com/66992566/110121871-5e187080-7dd8-11eb-8c44-ae9827e94cf6.png)

**Comment by bulgakovea** [comment]
Fixed in #30

**Comment by maistrenkoIulia** [comment]
verified
