### ISSUE TITLE
Code of dynamic attribute is not changed automatically when name is changed

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#48]
Jmix Studio plugin version: 1.0.SNAPSHOT2581-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC:
run add with dynamic attr>create new dynamic attr
set name = first
ER=AR: code =categoryfirst
edit attr>set name = second
ER: code =categorysecond
AR: code =categoryfirst
![image](https://user-images.githubusercontent.com/66992566/110123139-f5ca8e80-7dd9-11eb-9a58-ea2f2658f90c.png)

**Comment by knstvk** [comment]
@maistrenkoIulia - Is it changed automatically in CUBA?

**Comment by maistrenkoIulia** [comment]
@knstvk no. once generated, it doesn't change value autonaticlly

**Comment by andreysubbotin** [comment]
Not a bug. The editor generates code only if the code is empty (the same is in CUBA).
