### ISSUE TITLE
Impossible to create assotiation with Category

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#49]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC:
create new project 
add dynamic attr component
create entity add attribute association with type any to one with Category
ER: Category should be in droprown list
AR: no Category  in droprown list
![image](https://user-images.githubusercontent.com/66992566/110950307-1e640280-835d-11eb-9138-3c92236f4605.png)

**Comment by knstvk** [comment]
Why is this issue here and on Studio?

**Comment by andreysubbotin** [comment]
Because the `Category` entity is a system-level entity. Removing system-level annotation is required.
