### ISSUE TITLE
Its`s possible to create several categories with is default = true

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#50]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC:
create the project with dynamic attribute component
create entity
run app
admininstarion -> dynamic attributes
create category -> set  is default = true
create second category for the same entity -> set  is default = true
ER: flag   is default  for first category should reset
AR:
![image](https://user-images.githubusercontent.com/66992566/110950423-43f10c00-835d-11eb-8010-02dd06a93f21.png)

**Comment by maistrenkoIulia** [comment]
reproduced on 
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2820-211
IntelliJ version: IntelliJ IDEA 2021.1 (Community Edition)

**Comment by bulgakovea** [comment]
Can't reproduce. 
TC 1 :
1 - create Category "t1". in editor check "Is default". Save
2 - create Category "t2". in editor check "Is default". Save.
Result:
t1 - Is default - unchecked
t2 - Is default - checked

TC 2:
1 - create Category "t1" and "t2" with unchecked "Is default"
2 - check t1 "Is default". save
3 - check t2 "Is default". save
Result:
t1 - Is default - unchecked
t2 - Is default - checked

**Comment by maistrenkoIulia** [comment]
reproduced
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2876-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

![image.png](https://images.zenhubusercontent.com/5f0d7237622df466164dea0a/66ab7aca-5572-4ee2-99a9-66f2779165ce)

**Comment by bulgakovea** [comment]
@maistrenkoIulia 
Actually, this is the expected behavior of the system. 
You are trying to create a category for multiple entity types (in this case, "user" and "person"). 
Each entity type can have its own default category.

**Comment by maistrenkoIulia** [comment]
verified
