### ISSUE TITLE
Rework Categorized interface for entity

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#51]
Now it not convinient to create categorized entity
User has to create assotiation with Category > navogate to text tab > implenemt Categorized interface 
add core from getter/setter to overriden mithods, remove getter/setter

(Need to implement studio support in case new implementation)

**Comment by knstvk** [comment]
Create an issue for Studio.

**Comment by andreysubbotin** [comment]
It looks like an enhancement. Using categorized entity without Categorized interface, for example with annotations as audit annotations
