### ISSUE TITLE
Add validation for default value of enum dynamic attribute

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#52]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC:
create the project with dynamic attribute component
create entity
run app
admininstarion -> dynamic attributes
create category -> create attruibute with type = enum
enumeration -> edit -> add several values (1, 2, 3)
set default value =4
ER: it should be possible to set only predefined value (chage type of field ftom text fied to dropdown list with enum values)
AR:it`s possible to set any value
![image](https://user-images.githubusercontent.com/66992566/110953616-02626000-8361-11eb-9e9d-e8600850cc60.png)

**Comment by bulgakovea** [comment]
Fixed in #31
