### ISSUE TITLE
Missed Filter section in Dynamic Attributes > Category Browser

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#54]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2626-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

Administration > Dynamic Attributes
ER: standard filter section should be present
AR: Filter section is missed
![image](https://user-images.githubusercontent.com/66992566/110957321-f11b5280-8364-11eb-8a55-98cd45965f0c.png)

**Comment by knstvk** [comment]
No need for filter, there are always just a few records.

**Comment by maistrenkoIulia** [comment]
There is a filter section in Cuba platform
![image](https://user-images.githubusercontent.com/66992566/111618659-1513e380-87fe-11eb-8f83-0ef17da719a0.png)
