### ISSUE TITLE
Calculated values and options  tab doesn't save values

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#58]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2639-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: 
dymanic attributes> create category>create attribute 'first'
create attribute 'second' >open Calculated values and options tab
set depends on = first
set Recalculation value = ` if (entity.getValue("+first") == null) return 1 else return entity.getValue("+first").length()`
Ok>Apply changes
View created attribute>Calculated values and options 
ER: values should be filed with the correct data
AR: values are empty
![image](https://user-images.githubusercontent.com/66992566/111124970-877c8d80-858a-11eb-8a43-08badabdd636.png)

**Comment by andreysubbotin** [comment]
Fixed in Haulmont/jmix-dynattr#57
