### ISSUE TITLE
Validation script of dynamic attr doesn`t work in case value of attr isn`t filled

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#60]
- env:
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2639-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

- TC:
for ref_Car entity create dynamic attr Integer type
set Validation script = if (value != 3) return "the value '${value}' is incorrect"
Apply changes
Cars browser>create don`t fill dymanic attr -> Save changes

- Expected behavior
Validation should be appeare

- Actual behavior
No validation

**Comment by bulgakovea** [comment]
Fixed in #57
