### ISSUE TITLE
Number format pattern doesn't store value

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#64]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2639-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: create dymanic attr with type Fixed-point number
set Number format pattern = "##,####,####"
ok
apply changes
open category attribute again
ER: Number format pattern = "##,####,####"
AR: Number format pattern is empty

**Comment by bulgakovea** [comment]
Fixed in #57
