### ISSUE TITLE
Constraint Wizard doesn't work for jpql 

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#65]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2639-202
IntelliJ version: IntelliJ IDEA 2020.3.2 (Community Edition)

TC: create dynamica attr with type Entity
set Lookup field = true
navigate to Calculated values and option
select jpql type
try to open Constraint Wizard 
ER: define query screen should be opened
AR: no screen openes

also need to change Constraint Wizard position like in was in Cuba
cuba:
![image](https://user-images.githubusercontent.com/66992566/111794691-ee2dde00-88df-11eb-9513-857ffc885767.png)

jmix:
![image](https://user-images.githubusercontent.com/66992566/111794732-f84fdc80-88df-11eb-8d64-2db6bf93fc25.png)

**Comment by andreysubbotin** [comment]
Remove button: https://github.com/Haulmont/jmix-dynattr/issues/33#issuecomment-790640347

**Comment by bulgakovea** [comment]
Fixed in #33
