### ISSUE TITLE
Calculated values and options tab doesn't show 'attribute depends on' if category has not been saved

### ISSUE THREAD

**Issue by owlet1997** [Haulmont/jmix-dynattr#66]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2697-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**TC:**
1. Create project -> add dynamic attributes add-on -> run app
2. Open Administration -> dymanic attributes
3. Create category -> create attribute 'first'
4. Create attribute 'second' -> open Calculated values and options tab
5. Set depends on = first
6. Set Recalculation value = if (entity.getValue("+first") == null) return 1 else return entity.getValue("+first").length() -> Ok
7. View second attribute -> tab Calculated values and options

**AR:**
 attribute depends on doesn't shown
![image.png](https://images.zenhubusercontent.com/5ffd7dc3b256a97bde8addb9/c20ab44f-3073-4a6c-9be6-2f9b6815d700)

**ER:**
 attribute depends on should be shown

**Comment by bulgakovea** [comment]
Shoul be fixed in #57. Сan not reproduce.
