### ISSUE TITLE
'Can't find getter for property 'displayName'' exception after entering the category name

### ISSUE THREAD

**Issue by m-orlova** [Haulmont/jmix-dynattr#71]
Project: [dynattr.zip](https://github.com/Haulmont/jmix-dynattr/files/6365650/dynattr.zip)

Steps to reproduce:
1. Open Administration -> Dynamic attributes
2. Click on the "Create"' button
3. Enter value in the "Name" field
4. Click on the Entity type combo box
AR: Exception is thrown:
![image](https://user-images.githubusercontent.com/71265042/115878941-2df56180-a45a-11eb-99b2-25e840e43368.png)

**Comment by maistrenkoIulia** [comment]
verified
