### ISSUE TITLE
Attributes duplicate in case move them to columns and back

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#73]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2838-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: dynamic attributes>category>create>create 2 attributes
navigate to 'attributes location' tab
set columns count = 2
move each attribute to a separate column
move each attribute back
AR:
![image](https://user-images.githubusercontent.com/66992566/117254728-cf68b400-ae59-11eb-912e-1e86dc117d63.png)

**Comment by bulgakovea** [comment]
can't reproduce

1. Create category
2. Create 2 attribute ( "t" and "t2")
3. Open Attribute location tab
4. Set columns count = 2
5. Moved "t" to Column 1
6. Moved "t2" to Column 2
7. Moved "t" and "t2" back to Attributes column.
Result:
![Screenshot 2021-05-17 164554.png](https://images.zenhubusercontent.com/6059a1c05f3c063663546eb8/8e4a5657-3523-472b-a50c-b1f1b9d44f1f)

**Comment by maistrenkoIulia** [comment]
verified
