### ISSUE TITLE
'You have unsaved changes' dialog window in case don`t make any changes in Category attribute editor

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#75]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2948-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: run app>dynamic attribute>create category>create category attrubute>save
edit category attrubute> don't make any changes>cancel
ER: no dialog window should be display
AR: 'You have unsaved changes' dialog window appears

**Comment by artemglinov** [comment]
@maistrenkoIulia I can't reproduce the bug as it's described. Perhaps it relates to a case when a previously created Category Attribute is not actually edited but 'OK' button in the editor of the Attribute is pushed and then canceling in the Category editor leads to the 'You have unsaved changes' dialog window. Is this a more accurate description?

**Comment by maistrenkoIulia** [comment]
1.0.0-SNAPSHOT - ok

**Comment by maistrenkoIulia** [comment]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition) 
Reproduced
![image](https://user-images.githubusercontent.com/66992566/122226892-7021a900-cec7-11eb-8c74-279b2e0444a3.png)
![image](https://user-images.githubusercontent.com/66992566/122226928-7879e400-cec7-11eb-9652-c9ac94ce13aa.png)

**Comment by maistrenkoIulia** [comment]
verified
