### ISSUE TITLE
Incorrect behavior of Move up/Move down buttons for dynamic attributes after creation new one

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#77]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC:
run the pp with dynamic attrs component>dymanic attribute>create some category> create several attributes
Create one move attribute
AR: for the upper attribute both Move up/Move down  buttons are available/
For medium attribute only Move down attribute is available

![image](https://user-images.githubusercontent.com/66992566/122362020-d3afe300-cf68-11eb-889f-63d9a4bb8cab.png)
![image](https://user-images.githubusercontent.com/66992566/122362046-dad6f100-cf68-11eb-8286-9ba54257eeb6.png)

**Comment by bulgakovea** [comment]
can't reproduce

**Comment by maistrenkoIulia** [comment]
![image](https://user-images.githubusercontent.com/66992566/125272525-01e0d280-e31d-11eb-839b-ff75352971dc.png)
![image](https://user-images.githubusercontent.com/66992566/125272685-305ead80-e31d-11eb-83b4-7f543bdfed50.png)


Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3217-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)

**Comment by bulgakovea** [comment]
can't reproduce by described case
