### ISSUE TITLE
Attribution location doesn't work correcty

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#78]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: run app with dynamic attr
create category>create several attributes
Navigate to tab Attributes location
set column count  = 4, drag each attr to the column
![image](https://user-images.githubusercontent.com/66992566/122367188-4327d180-cf6d-11eb-8d99-fb5b8a079311.png)

Save configuration> ok >Apply changes
Open entity editor
ER: there are should be 4 columns with attr in each
AR:
![image](https://user-images.githubusercontent.com/66992566/122368094-17591b80-cf6e-11eb-85b0-64dde74d03c4.png)

**Comment by andreysubbotin** [comment]
It works only with the `dynamicAttributePanel` component: https://docs.jmix.io/jmix/1.0/dyn-attr/dynattr-view.html#dynamicattributespanel
