### ISSUE TITLE
Impossible to set value for dynamic attribute with string type if is collection = true

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#82]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC:
run app> create dynamic attr type =string,  is collection = true
add visibility for screens
create entity>open lookup picker> try to sen any value>add
AR: value resets
![image](https://user-images.githubusercontent.com/66992566/122387222-b20e2600-cf7f-11eb-8b0a-ddbd981e4319.png)

**Comment by bulgakovea** [comment]
can't reproduce
![image](https://user-images.githubusercontent.com/32310903/124749190-f82e2800-df34-11eb-8367-90aca6b5cca6.png)

**Comment by maistrenkoIulia** [comment]
reproduces on
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3217-211
IntelliJ version: IntelliJ IDEA 2021.1.3 (Community Edition)
![image](https://user-images.githubusercontent.com/66992566/125273841-64869e00-e31e-11eb-8ade-6b85c9f0f0a4.png)

![image](https://user-images.githubusercontent.com/66992566/125273782-559feb80-e31e-11eb-94c3-d110390f677c.png)

**Comment by maistrenkoIulia** [comment]
verified
