### ISSUE TITLE
Impossible to set value in localization tab for enum attribute

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#83]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3071-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: run app with 2 locales  by user with role dynamic attributes admin
dynamic attribute> create attribute>set type = enum>enum browser
add enum values>select one>click on localization table
ER: it should be possible to edit localization values
AR: Impossible to set value in localization tab

![image](https://user-images.githubusercontent.com/66992566/122525424-459c3100-d02a-11eb-8ab6-583bb9f93d15.png)

relates to https://github.com/Haulmont/jmix-dynattr/issues/38

**Comment by bulgakovea** [comment]
master commit 16e1e2b96cd3d2484f094e4d35efc0b79e9a17da

**Comment by maistrenkoIulia** [comment]
verified
