### ISSUE TITLE
NPE during close Browser with dynamic attribute

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-dynattr#86]
relates to https://github.com/Haulmont/jmix-dynattr/issues/84

Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3147-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)
[trdynattr.zip](https://github.com/Haulmont/jmix-dynattr/files/6732842/trdynattr.zip)

Open project trdynattr.zip 
Run app
Remove Dyn attr category and apply changes
Create same Dyn attr category and attributes for the User entity and apply it
Open and close User browse
Expected result:
Browser opened and closed without any exception. Dynamic attributes are displayed in the table

**Comment by bulgakovea** [comment]
It looks like the tables did not save the changes about the UI config.
Case: 

- Open project trdynattr.zip
- Run app
- Remove Dyn attr category and apply changes
- Open and close User browser (now UI params should be saved correct)
- Create same Dyn attr category and attributes for the User entity and apply it
- Open and close browser now
ER: 
Browser opened and closed without any exception. Dynamic attributes are displayed in the table
